use_frameworks!

target 'ICLabel_Example' do
  pod 'ICLabel', :path => '../'

  target 'ICLabel_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
